### ISSUE TITLE
Error when migrating api keys

### ISSUE THREAD

**Issue by Mantrain** [reportportal/migrations-complex#16]
I get this error when running migrations. Upgrading from 5.7.4 to 23.2

```
Caused by: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [INSERT INTO public.api_keys (name, hash, created_at, user_id) VALUES (?, ?, ?, ?)]; ERROR: duplicate key value violates unique constraint "users_api_keys_unique"
  Detail: Key (name, user_id)=(Legacy API Key, 27) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_api_keys_unique"
  Detail: Key (name, user_id)=(Legacy API Key, 27) already exists.
```

Here is the full error stack.

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-10-16 13:51:25.449 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785) ~[spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) ~[spring-boot-2.4.3.jar!/:2.4.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.4.3.jar!/:2.4.3]
	at com.epam.reportportal.ComplexMigrationsApplication.main(ComplexMigrationsApplication.java:21) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[complex-migrations-1.0.0-exec.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107) ~[complex-migrations-1.0.0-exec.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[complex-migrations-1.0.0-exec.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[complex-migrations-1.0.0-exec.jar:na]
Caused by: org.springframework.dao.DuplicateKeyException: PreparedStatementCallback; SQL [INSERT INTO public.api_keys (name, hash, created_at, user_id) VALUES (?, ?, ?, ?)]; ERROR: duplicate key value violates unique constraint "users_api_keys_unique"
  Detail: Key (name, user_id)=(Legacy API Key, 27) already exists.; nested exception is org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_api_keys_unique"
  Detail: Key (name, user_id)=(Legacy API Key, 27) already exists.
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:691) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:1034) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
	at com.epam.reportportal.service.impl.TokenMigrationService.migrate(TokenMigrationService.java:54) ~[classes!/:na]
	at com.epam.reportportal.service.impl.TokenMigrationService$$FastClassBySpringCGLIB$$d9c28b0f.invoke(<generated>) ~[classes!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at com.epam.reportportal.logging.LogAspect.logMigration(LogAspect.java:19) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.4.jar!/:5.3.4]
	at com.epam.reportportal.service.impl.TokenMigrationService$$EnhancerBySpringCGLIB$$f9d70933.migrate(<generated>) ~[classes!/:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541) ~[na:na]
	at com.epam.reportportal.service.impl.ComplexMigrationService.migrate(ComplexMigrationService.java:29) ~[classes!/:na]
	at com.epam.reportportal.ComplexMigrationsApplication.run(ComplexMigrationsApplication.java:26) ~[classes!/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.4.3.jar!/:2.4.3]
	... 13 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "users_api_keys_unique"
  Detail: Key (name, user_id)=(Legacy API Key, 27) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553) ~[postgresql-42.2.18.jar!/:42.2.18]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285) ~[postgresql-42.2.18.jar!/:42.2.18]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:521) ~[postgresql-42.2.18.jar!/:42.2.18]
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:870) ~[postgresql-42.2.18.jar!/:42.2.18]
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:893) ~[postgresql-42.2.18.jar!/:42.2.18]
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644) ~[postgresql-42.2.18.jar!/:42.2.18]
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128) ~[HikariCP-3.4.5.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java) ~[HikariCP-3.4.5.jar!/:na]
	at org.springframework.jdbc.core.JdbcTemplate.lambda$batchUpdate$4(JdbcTemplate.java:1048) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
	... 41 common frames omitted
```

**Comment by hlebkanonik** [comment]
Hi! I apologize for the delayed response. These steps will assist you in a successful migration:
1. Migrate API keys
2. Migrate from multi-bucket to single 
3. Migrate from MinIO to S3

[Link to the documentation](https://github.com/reportportal/migrations-complex/tree/master?tab=readme-ov-file#migrations-functionality)

We have updated the API keys flow starting from release v23.1

**Comment by Mantrain** [comment]
Thank you. 

I have now tried again with the latest version of complex migrations. I am still upgrading from 5.7.4.


I get another error:


```
2024-09-17 08:20:15.908  INFO 1 --- [           main] c.e.r.ComplexMigrationsApplication       : Starting ComplexMigrationsApplication using Java 11.0.17 on 4b09ddcaa6bc with PID 1 (/complex-migrations-1.0.0-exec.jar started by root in /)
2024-09-17 08:20:15.928  INFO 1 --- [           main] c.e.r.ComplexMigrationsApplication       : No active profile set, falling back to default profiles: default
2024-09-17 08:20:20.762  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8686 (http)
2024-09-17 08:20:20.791  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-09-17 08:20:20.792  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.43]
2024-09-17 08:20:21.074  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-09-17 08:20:21.075  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 4949 ms
2024-09-17 08:20:21.874  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'complexMigrationsApplication': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'complexMigrationService' defined in URL [jar:file:/complex-migrations-1.0.0-exec.jar!/BOOT-INF/classes!/com/epam/reportportal/service/impl/ComplexMigrationService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tokenMigrationService' defined in URL [jar:file:/complex-migrations-1.0.0-exec.jar!/BOOT-INF/classes!/com/epam/reportportal/service/impl/TokenMigrationService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.jdbc.core.JdbcTemplate' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
2024-09-17 08:20:21.883  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-09-17 08:20:21.943  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-09-17 08:20:21.998 ERROR 1 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in com.epam.reportportal.service.impl.TokenMigrationService required a bean of type 'org.springframework.jdbc.core.JdbcTemplate' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.jdbc.core.JdbcTemplate' in your configuration.
```

**Comment by Mantrain** [comment]
After many tears and much anger I figured out that somehow two users in the database has two oauth tokens, and thus the migration failed.

```
 DELETE FROM public.oauth_access_token WHERE user_id = '27';
```
